---
title: "Packages - Part 1"
author: "Brian A. Fannin"
output:
  revealjs::revealjs_presentation:
    center: no
    css: ./css/revealOpts.css
    reveal_plugins:
    - notes
    - zoom
    self_contained: no
    theme: solarized
    transition: slide
---

```{r echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(knitr))
knitr::opts_chunk$set(
    warning=FALSE
  , error=FALSE
  , echo=FALSE
  , message=FALSE
  , fig.height = 4.5
  , fig.pos="t"
  , collapse = TRUE
)
knitr::opts_knit$set(root.dir = normalizePath('../'))
```

##

This is the most important thing that you will do today.

## Why?

* Won't clutter up the global namespace
* Basic unit of code currency
* Allows functionality to be shared across an enterprise
* Encourages disciplined coding

## What?

* A package is a set of functions.
* A package may also have data.
* A package has (or should have) lots and lots of documentation.
* A package must adhere to certain standards, which ensures that users may rely on them.


## Who?

CRAN

Picture a bunch of angry old dudes at European universities in tweed jackets.

## Where?

Most packages are hosted on CRAN. Also loads hosted on bioconductor, but probably of less interest to actuaries.

Beta releases of CRAN packages are often found on GitHub or other cloud platforms. This is also where to find non-CRAN, off-label garage band stuff. Some of it's good. Some of it isn't.

## How?

After the break ...
